[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eolib = "1.0.0-RC8"
futures-util = "0.3.30"
tokio = {version = "1.38.0", features = ["full"]}
tokio-tungstenite = "0.23.1"
